# Generated by Django 5.1.2 on 2024-10-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='video')),
                ('description', models.TextField(max_length=200, verbose_name='description')),
                ('file', models.FileField(upload_to='videos_file')),
            ],
        ),
    ]
