# Generated by Django 5.1.2 on 2024-10-30 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='category_name')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='email address')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('gender', models.CharField(default='man', max_length=1)),
                ('country', models.CharField(blank=True, max_length=20, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='Регион')),
                ('locality', models.CharField(blank=True, max_length=40, verbose_name='Населеный пункт')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.category_course', verbose_name='course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
