# Generated by Django 5.1.2 on 2024-10-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.FileField(null=True, upload_to='Avatar'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=models.CharField(max_length=20, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='locality',
            field=models.CharField(max_length=40, null=True, verbose_name='Населеный пункт'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='patronymic',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='region',
            field=models.CharField(max_length=50, null=True, verbose_name='Регион'),
        ),
    ]
